Fix RSpec/ChangeByZero with compound operators
rubocop/rubocop-rspec pull request #1324
Opened 2022-07-11 23:11 UTC by BrianHawley

Previously, it didn't recognize compound expressions using `&` or `|`.
This led it to correct part of the expressions as regular code, but the
generated code was malformed.

Now it recognizes compound expressions using the operators.

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [ ] Updated documentation.
* [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

If you have created a new cop:

* [ ] Added the new cop to `config/default.yml`.
* [ ] The cop is configured as `Enabled: pending` in `config/default.yml`.
* [ ] The cop is configured as `Enabled: true` in `.rubocop.yml`.
* [ ] The cop documents examples of good and bad code.
* [ ] The tests assert both that bad code is reported and that good code is not reported.
* [ ] Set `VersionAdded` in `default/config.yml` to the next minor version.

If you have modified an existing cop's configuration options:

* [ ] Set `VersionChanged` in `config/default.yml` to the next major version.

2022-07-11 23:17 UTC, BrianHawley commented
@pirj you reviewed and merged the previous PRs for this cop. Care to take a look at this change?

2022-07-11 23:22 UTC, pirj approved these changes
Fantastic, thanks!

2022-07-11 23:25 UTC, BrianHawley commented
I just thought of another bad correction. Give me a second.

2022-07-11 23:47 UTC, pirj requested changes
RSpec wouldn't allow `.not_to change { }.by(...)` to my best knowledge.

2022-07-11 23:53 UTC, BrianHawley commented
@pirj you're right, it looks like rspec complains about that now. I remember it allowing that back in the day, so it's good to see it complaining now. This gem probably doesn't support rspec versions that old, so I'll remove it.

2022-07-11 23:59 UTC, BrianHawley commented
@pirj see https://github.com/rspec/rspec-expectations/blob/main/Changelog.md#300beta2--2014-02-17 for details.

2022-07-12 00:07 UTC, BrianHawley commented
@pirj do you still want me to undo the `not_to` and `to_not` support? As it is, with that support, it changes code that rspec complains about to semantically equivalent code that it wouldn't complain about. It might help those unfortunates who still have to do rspec 3 updates in this day and age.

2022-07-12 00:12 UTC, pirj commented
> if rubocop-rspec supports rspec 2.x or earlier

It's a good question. I would say we don't, as **probably** those with RSpec 2.x are on early Ruby 2.0/2.1 which we don't support. Might be Ruby version update is an easier task than RSpec 2 -> 3 migration.

But not to be overly defensive with our code, I'd remove this, and wait for someone to complain about this deficiency. We can reconsider if this happens.

2022-07-12 00:24 UTC, BrianHawley commented
@pirj I just made it skip the bad correction in that case, so it at least doesn't introduce logic errors.

2022-07-12 07:42 UTC, pirj approved these changes
Thanks!

2022-07-12 08:46 UTC, Darhazer commented
Wow I haven't seens specs using that syntax. Do we need a cop to force using `and` and `or` over `&` and `|`

2022-07-12 10:37 UTC, pirj commented
I don’t know.
Those are aliases to or and and.
I’d check existing codebases if they make use of them.
Some may prefer it, and I personally kind of like how it looks like.

2022-07-12 10:40 UTC, Darhazer commented
> Some may prefer it, and I personally kind of like how it looks like.

That's why the configurable enforced styles are ;)

2022-07-12 14:26 UTC, BrianHawley commented
The `&` and `|` operators are better to use sometimes because their precedence is a better match for the circumstances, and they don't get caught up in enforced parentheses like `and` and `or` are (as I am subjected to at work). If you make a cop to prevent their use, make sure that there's an option to enforce their use, or at least to disable it.

2022-07-12 15:03 UTC, pirj commented
My apologies to let the discussion drift. @BrianHawley you are really welcome to open an issue or a PR for the new cop, and to add some reasoning. I'll do my best to find some proof of usage of `&`/`|` in the wild. I confess knowing about this syntax, and being frustrated with `and`/`or` at times, and never giving `&`/`|` a shot. Might be the cop, even with the opposite enforced style could spread the word about such an alternative.

2022-07-12 18:34 UTC, merged

2022-07-12 18:34 UTC, pirj commented
Thank you, @BrianHawley !