add configure doc for empty_example_group.rb
rubocop/rubocop-rspec pull request #1653
Opened 2023-05-29 02:16 UTC by kuboon

https://github.com/rubocop/rubocop-rspec/blob/cd6a30efa9094e389cf9e4dd473b7631fe18bab1/docs/modules/ROOT/pages/upgrade_to_version_2.adoc#adjust-the-configuration-of-rspecemptyexamplegroup
______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [ ] Added tests.
- [x] Updated documentation.
- [ ] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [ ] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

If you have created a new cop:

- [ ] Added the new cop to `config/default.yml`.
- [ ] The cop is configured as `Enabled: pending` in `config/default.yml`.
- [ ] The cop is configured as `Enabled: true` in `.rubocop.yml`.
- [ ] The cop documents examples of good and bad code.
- [ ] The tests assert both that bad code is reported and that good code is not reported.
- [ ] Set `VersionAdded: "<<next>>"` in `default/config.yml`.

If you have modified an existing cop's configuration options:

- [ ] Set `VersionChanged: "<<next>>"` in `config/default.yml`.

2023-05-29 09:03 UTC, ydah commented on lib/rubocop/cop/rspec/empty_example_group.rb
> +      # end
I think the following fix will address the RuboCop failure in CI.

```suggestion
      # @example configuration
      # # .rubocop.yml
      # RSpec:
      #   Language:
      #     Includes:
      #       Examples:
      #         - include_tests
      #
      # # spec_helper.rb
      # RSpec.configure do |config|
      #   config.alias_it_behaves_like_to(:include_tests)
      # end
      #
      # # bacon_spec.rb
      # describe Bacon do
      #   let(:bacon)      { Bacon.new(chunkiness) }
      #   let(:chunkiness) { false                 }
      #
      #   context 'extra chunky' do   # not flagged by rubocop
      #     let(:chunkiness) { true }
      #
      #     include_tests 'shared tests'
      #   end
      # end
```

2023-05-29 15:09 UTC, pirj commented on lib/rubocop/cop/rspec/empty_example_group.rb
> +      # RSpec:
I think you should increase indentation. Run `rake` so it builds docs to see for sure

2023-07-22 15:08 UTC, pirj requested changes
We have numerous cops that can be indirectly configured with our RSpec DSL configuration.
Are there existing examples of documenting DSL configuration for other cops?
I’d rather made a separate section in our documentation to make this claret if it is not yet clear how to configure this and what the effects are.

2023-07-26 03:40 UTC, kuboon commented
https://github.com/rubocop/rubocop-rspec/blob/v2.22.0/lib/rubocop/cop/rspec/multiple_expectations.rb#L51-L62

https://github.com/search?q=repo%3Arubocop%2Frubocop-rspec%20%40example%20configuration&type=code

2023-07-26 05:06 UTC, ydah commented
I think it would be good to summarize it in the next section:
https://docs.rubocop.org/rubocop-rspec/usage.html#rspec-dsl-configuration

2023-07-26 05:07 UTC, ydah requested changes
I think it would be good to summarize it in the following section:
https://docs.rubocop.org/rubocop-rspec/usage.html#rspec-dsl-configuration

2024-04-04 05:08 UTC, closed without merging